import type { ContentItem } from "@/types";

/**
 * Curated library of inspirational quotes, pre-formatted for the 6x22 Vestaboard grid.
 * All text must be uppercase and fit within 22 characters per line, 6 lines total.
 */
export const QUOTES: ContentItem[] = [
  {
    id: "jobs-hungry",
    type: "quote",
    lines: [
      "",
      "    STAY HUNGRY.",
      "    STAY FOOLISH.",
      "",
      "    - STEVE JOBS",
      "",
    ],
  },
  {
    id: "mies-details",
    type: "quote",
    lines: [
      "",
      "    GOD IS IN",
      "    THE DETAILS.",
      "",
      "    - LUDWIG MIES",
      "",
    ],
  },
  {
    id: "jobs-great-work",
    type: "quote",
    lines: [
      "  THE ONLY WAY TO",
      "  DO GREAT WORK IS",
      "  TO LOVE WHAT",
      "  YOU DO.",
      "",
      "    - STEVE JOBS",
    ],
  },
  {
    id: "davinci-simplicity",
    type: "quote",
    lines: [
      "",
      " SIMPLICITY IS THE",
      " ULTIMATE",
      " SOPHISTICATION.",
      "",
      " - LEONARDO DA VINCI",
    ],
  },
  {
    id: "franklin-well-done",
    type: "quote",
    lines: [
      "",
      " WELL DONE IS BETTER",
      " THAN WELL SAID.",
      "",
      " - BENJAMIN FRANKLIN",
      "",
    ],
  },
  {
    id: "mies-less-more",
    type: "quote",
    lines: [
      "",
      "    LESS IS MORE.",
      "",
      "    - LUDWIG MIES",
      "    VAN DER ROHE",
      "",
    ],
  },
  {
    id: "einstein-imagination",
    type: "quote",
    lines: [
      "",
      " IMAGINATION IS MORE",
      " IMPORTANT THAN",
      " KNOWLEDGE.",
      "",
      " - ALBERT EINSTEIN",
    ],
  },
  {
    id: "gandhi-change",
    type: "quote",
    lines: [
      "",
      " BE THE CHANGE YOU",
      " WISH TO SEE IN",
      " THE WORLD.",
      "",
      " - MAHATMA GANDHI",
    ],
  },
  {
    id: "twain-right",
    type: "quote",
    lines: [
      " DO THE RIGHT THING.",
      " IT WILL GRATIFY",
      " SOME PEOPLE AND",
      " ASTONISH THE REST.",
      "",
      " - MARK TWAIN",
    ],
  },
  {
    id: "bruce-lee-limits",
    type: "quote",
    lines: [
      " THERE ARE NO LIMITS",
      " ONLY PLATEAUS, AND",
      " YOU MUST NOT STAY",
      " THERE.",
      "",
      " - BRUCE LEE",
    ],
  },
  {
    id: "disney-dream",
    type: "quote",
    lines: [
      "",
      " ALL OUR DREAMS CAN",
      " COME TRUE IF WE",
      " HAVE THE COURAGE",
      " TO PURSUE THEM.",
      " - WALT DISNEY",
    ],
  },
  {
    id: "churchill-never",
    type: "quote",
    lines: [
      "",
      " NEVER NEVER NEVER",
      " GIVE UP.",
      "",
      " - WINSTON CHURCHILL",
      "",
    ],
  },
  {
    id: "confucius-journey",
    type: "quote",
    lines: [
      " A JOURNEY OF A",
      " THOUSAND MILES",
      " BEGINS WITH A",
      " SINGLE STEP.",
      "",
      " - CONFUCIUS",
    ],
  },
  {
    id: "picasso-action",
    type: "quote",
    lines: [
      "",
      " ACTION IS THE",
      " FOUNDATIONAL KEY",
      " TO ALL SUCCESS.",
      "",
      " - PABLO PICASSO",
    ],
  },
  {
    id: "thoreau-forward",
    type: "quote",
    lines: [
      "",
      " GO CONFIDENTLY IN",
      " THE DIRECTION OF",
      " YOUR DREAMS.",
      "",
      " - HENRY THOREAU",
    ],
  },
  {
    id: "emerson-journey",
    type: "quote",
    lines: [
      " LIFE IS A JOURNEY",
      " NOT A DESTINATION.",
      "",
      " - RALPH WALDO",
      "   EMERSON",
      "",
    ],
  },
  {
    id: "aristotle-excellence",
    type: "quote",
    lines: [
      " WE ARE WHAT WE",
      " REPEATEDLY DO.",
      " EXCELLENCE IS NOT",
      " AN ACT BUT",
      " A HABIT.",
      " - ARISTOTLE",
    ],
  },
  {
    id: "ford-whether",
    type: "quote",
    lines: [
      " WHETHER YOU THINK",
      " YOU CAN OR YOU",
      " THINK YOU CANT",
      " YOURE RIGHT.",
      "",
      " - HENRY FORD",
    ],
  },
  {
    id: "mandela-impossible",
    type: "quote",
    lines: [
      "",
      " IT ALWAYS SEEMS",
      " IMPOSSIBLE UNTIL",
      " ITS DONE.",
      "",
      " - NELSON MANDELA",
    ],
  },
  {
    id: "aurelius-obstacle",
    type: "quote",
    lines: [
      " THE IMPEDIMENT TO",
      " ACTION ADVANCES",
      " ACTION. WHAT STANDS",
      " IN THE WAY BECOMES",
      " THE WAY.",
      " - MARCUS AURELIUS",
    ],
  },
  {
    id: "lao-tzu-master",
    type: "quote",
    lines: [
      " A MASTER IN THE",
      " ART OF LIVING",
      " DRAWS NO SHARP",
      " DISTINCTION BETWEEN",
      " WORK AND PLAY.",
      " - LAO TZU",
    ],
  },
  {
    id: "seneca-luck",
    type: "quote",
    lines: [
      "",
      " LUCK IS WHAT",
      " HAPPENS WHEN",
      " PREPARATION MEETS",
      " OPPORTUNITY.",
      " - SENECA",
    ],
  },
  {
    id: "tesla-present",
    type: "quote",
    lines: [
      " THE PRESENT IS",
      " THEIRS. THE FUTURE",
      " FOR WHICH I REALLY",
      " WORKED IS MINE.",
      "",
      " - NIKOLA TESLA",
    ],
  },
  {
    id: "hemingway-write",
    type: "quote",
    lines: [
      "",
      " WRITE HARD AND",
      " CLEAR ABOUT WHAT",
      " HURTS.",
      "",
      " - ERNEST HEMINGWAY",
    ],
  },
  {
    id: "sagan-pale-dot",
    type: "quote",
    lines: [
      " LOOK AGAIN AT",
      " THAT DOT. THATS",
      " HERE. THATS HOME.",
      " THATS US.",
      "",
      " - CARL SAGAN",
    ],
  },
  {
    id: "feynman-understand",
    type: "quote",
    lines: [
      " IF YOU CANT EXPLAIN",
      " IT SIMPLY YOU DONT",
      " UNDERSTAND IT WELL",
      " ENOUGH.",
      "",
      " - RICHARD FEYNMAN",
    ],
  },
  {
    id: "watts-present",
    type: "quote",
    lines: [
      " THE ONLY WAY TO",
      " MAKE SENSE OUT OF",
      " CHANGE IS TO PLUNGE",
      " INTO IT AND JOIN",
      " THE DANCE.",
      " - ALAN WATTS",
    ],
  },
  {
    id: "camus-invincible",
    type: "quote",
    lines: [
      " IN THE MIDST OF",
      " WINTER I FOUND",
      " THERE WAS WITHIN",
      " ME AN INVINCIBLE",
      " SUMMER.",
      " - ALBERT CAMUS",
    ],
  },
  {
    id: "ada-lovelace",
    type: "quote",
    lines: [
      " THAT BRAIN OF MINE",
      " IS SOMETHING MORE",
      " THAN MERELY MORTAL",
      " AS TIME WILL SHOW.",
      "",
      " - ADA LOVELACE",
    ],
  },
  {
    id: "curie-curious",
    type: "quote",
    lines: [
      " BE LESS CURIOUS",
      " ABOUT PEOPLE AND",
      " MORE CURIOUS ABOUT",
      " IDEAS.",
      "",
      " - MARIE CURIE",
    ],
  },
];
